export const countriesData = [
  { label: "Afghanistan", value: "Afghanistan", code: "93", nationality: "Afghan" },
  { label: "Albania", value: "Albania", code: "355", nationality: "Albanian" },
  { label: "Algeria", value: "Algeria", code: "213", nationality: "Algerian" },
  { label: "Andorra", value: "Andorra", code: "376", nationality: "Andorran" },
  { label: "Angola", value: "Angola", code: "244", nationality: "Angolan" },
  { label: "Argentina", value: "Argentina", code: "54", nationality: "Argentine" },
  { label: "Armenia", value: "Armenia", code: "374", nationality: "Armenian" },
  { label: "Australia", value: "Australia", code: "61", nationality: "Australian" },
  { label: "Austria", value: "Austria", code: "43", nationality: "Austrian" },
  { label: "Azerbaijan", value: "Azerbaijan", code: "994", nationality: "Azerbaijani" },
  { label: "Bahamas", value: "Bahamas", code: "1-242", nationality: "Bahamian" },
  { label: "Bahrain", value: "Bahrain", code: "973", nationality: "Bahraini" },
  { label: "Bangladesh", value: "Bangladesh", code: "880", nationality: "Bangladeshi" },
  { label: "Barbados", value: "Barbados", code: "1-246", nationality: "Barbadian" },
  { label: "Belarus", value: "Belarus", code: "375", nationality: "Belarusian" },
  { label: "Belgium", value: "Belgium", code: "32", nationality: "Belgian" },
  { label: "Belize", value: "Belize", code: "501", nationality: "Belizean" },
  { label: "Benin", value: "Benin", code: "229", nationality: "Beninese" },
  { label: "Bhutan", value: "Bhutan", code: "975", nationality: "Bhutanese" },
  { label: "Bolivia", value: "Bolivia", code: "591", nationality: "Bolivian" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina", code: "387", nationality: "Bosnian" },
  { label: "Botswana", value: "Botswana", code: "267", nationality: "Botswanan" },
  { label: "Brazil", value: "Brazil", code: "55", nationality: "Brazilian" },
  { label: "Brunei", value: "Brunei", code: "673", nationality: "Bruneian" },
  { label: "Bulgaria", value: "Bulgaria", code: "359", nationality: "Bulgarian" },
  { label: "Burkina Faso", value: "Burkina Faso", code: "226", nationality: "Burkinabè" },
  { label: "Burundi", value: "Burundi", code: "257", nationality: "Burundian" },
  { label: "Cambodia", value: "Cambodia", code: "855", nationality: "Cambodian" },
  { label: "Cameroon", value: "Cameroon", code: "237", nationality: "Cameroonian" },
  { label: "Canada", value: "Canada", code: "1", nationality: "Canadian" },
  { label: "Cape Verde", value: "Cape Verde", code: "238", nationality: "Cape Verdean" },
  { label: "Central African Republic", value: "Central African Republic", code: "236", nationality: "Central African" },
  { label: "Chad", value: "Chad", code: "235", nationality: "Chadian" },
  { label: "Chile", value: "Chile", code: "56", nationality: "Chilean" },
  { label: "China", value: "China", code: "86", nationality: "Chinese" },
  { label: "Colombia", value: "Colombia", code: "57", nationality: "Colombian" },
  { label: "Comoros", value: "Comoros", code: "269", nationality: "Comoran" },
  { label: "Costa Rica", value: "Costa Rica", code: "506", nationality: "Costa Rican" },
  { label: "Croatia", value: "Croatia", code: "385", nationality: "Croatian" },
  { label: "Cuba", value: "Cuba", code: "53", nationality: "Cuban" },
  { label: "Cyprus", value: "Cyprus", code: "357", nationality: "Cypriot" },
  { label: "Czech Republic", value: "Czech Republic", code: "420", nationality: "Czech" },
  { label: "Denmark", value: "Denmark", code: "45", nationality: "Danish" },
  { label: "Djibouti", value: "Djibouti", code: "253", nationality: "Djiboutian" },
  { label: "Dominican Republic", value: "Dominican Republic", code: "1-809", nationality: "Dominican" },
  { label: "DR Congo", value: "DR Congo", code: "243", nationality: "Congolese" },
  { label: "Ecuador", value: "Ecuador", code: "593", nationality: "Ecuadorian" },
  { label: "Egypt", value: "Egypt", code: "20", nationality: "Egyptian" },
  { label: "El Salvador", value: "El Salvador", code: "503", nationality: "Salvadoran" },
  { label: "Estonia", value: "Estonia", code: "372", nationality: "Estonian" },
  { label: "Ethiopia", value: "Ethiopia", code: "251", nationality: "Ethiopian" },
  { label: "Fiji", value: "Fiji", code: "679", nationality: "Fijian" },
  { label: "Finland", value: "Finland", code: "358", nationality: "Finnish" },
  { label: "France", value: "France", code: "33", nationality: "French" },
  { label: "Gabon", value: "Gabon", code: "241", nationality: "Gabonese" },
  { label: "Gambia", value: "Gambia", code: "220", nationality: "Gambian" },
  { label: "Georgia", value: "Georgia", code: "995", nationality: "Georgian" },
  { label: "Germany", value: "Germany", code: "49", nationality: "German" },
  { label: "Ghana", value: "Ghana", code: "233", nationality: "Ghanaian" },
  { label: "Greece", value: "Greece", code: "30", nationality: "Greek" },
  { label: "Guatemala", value: "Guatemala", code: "502", nationality: "Guatemalan" },
  { label: "Haiti", value: "Haiti", code: "509", nationality: "Haitian" },
  { label: "Honduras", value: "Honduras", code: "504", nationality: "Honduran" },
  { label: "Hong Kong", value: "Hong Kong", code: "852", nationality: "Hong Konger" },
  { label: "Hungary", value: "Hungary", code: "36", nationality: "Hungarian" },
  { label: "Iceland", value: "Iceland", code: "354", nationality: "Icelandic" },
  { label: "India", value: "India", code: "91", nationality: "Indian" },
  { label: "Indonesia", value: "Indonesia", code: "62", nationality: "Indonesian" },
  { label: "Iran", value: "Iran", code: "98", nationality: "Iranian" },
  { label: "Iraq", value: "Iraq", code: "964", nationality: "Iraqi" },
  { label: "Ireland", value: "Ireland", code: "353", nationality: "Irish" },
  { label: "Israel", value: "Israel", code: "972", nationality: "Israeli" },
  { label: "Italy", value: "Italy", code: "39", nationality: "Italian" },
  { label: "Japan", value: "Japan", code: "81", nationality: "Japanese" },
  { label: "Jordan", value: "Jordan", code: "962", nationality: "Jordanian" },
  { label: "Kazakhstan", value: "Kazakhstan", code: "7", nationality: "Kazakhstani" },
  { label: "Kenya", value: "Kenya", code: "254", nationality: "Kenyan" },
  { label: "Kuwait", value: "Kuwait", code: "965", nationality: "Kuwaiti" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan", code: "996", nationality: "Kyrgyz" },
  { label: "Laos", value: "Laos", code: "856", nationality: "Laotian" },
  { label: "Latvia", value: "Latvia", code: "371", nationality: "Latvian" },
  { label: "Lebanon", value: "Lebanon", code: "961", nationality: "Lebanese" },
  { label: "Liberia", value: "Liberia", code: "231", nationality: "Liberian" },
  { label: "Libya", value: "Libya", code: "218", nationality: "Libyan" },
  { label: "Lithuania", value: "Lithuania", code: "370", nationality: "Lithuanian" },
  { label: "Luxembourg", value: "Luxembourg", code: "352", nationality: "Luxembourgish" },
  { label: "Madagascar", value: "Madagascar", code: "261", nationality: "Malagasy" },
  { label: "Malaysia", value: "Malaysia", code: "60", nationality: "Malaysian" },
  { label: "Maldives", value: "Maldives", code: "960", nationality: "Maldivian" },
  { label: "Mali", value: "Mali", code: "223", nationality: "Malian" },
  { label: "Malta", value: "Malta", code: "356", nationality: "Maltese" },
  { label: "Mauritius", value: "Mauritius", code: "230", nationality: "Mauritian" },
  { label: "Mexico", value: "Mexico", code: "52", nationality: "Mexican" },
  { label: "Moldova", value: "Moldova", code: "373", nationality: "Moldovan" },
  { label: "Mongolia", value: "Mongolia", code: "976", nationality: "Mongolian" },
  { label: "Montenegro", value: "Montenegro", code: "382", nationality: "Montenegrin" },
  { label: "Morocco", value: "Morocco", code: "212", nationality: "Moroccan" },
  { label: "Myanmar", value: "Myanmar", code: "95", nationality: "Burmese" },
  { label: "Nepal", value: "Nepal", code: "977", nationality: "Nepali" },
  { label: "Netherlands", value: "Netherlands", code: "31", nationality: "Dutch" },
  { label: "New Zealand", value: "New Zealand", code: "64", nationality: "New Zealander" },
  { label: "Nicaragua", value: "Nicaragua", code: "505", nationality: "Nicaraguan" },
  { label: "Niger", value: "Niger", code: "227", nationality: "Nigerien" },
  { label: "Nigeria", value: "Nigeria", code: "234", nationality: "Nigerian" },
  { label: "North Korea", value: "North Korea", code: "850", nationality: "North Korean" },
  { label: "Norway", value: "Norway", code: "47", nationality: "Norwegian" },
  { label: "Oman", value: "Oman", code: "968", nationality: "Omani" },
  { label: "Pakistan", value: "Pakistan", code: "92", nationality: "Pakistani" },
  { label: "Panama", value: "Panama", code: "507", nationality: "Panamanian" },
  { label: "Paraguay", value: "Paraguay", code: "595", nationality: "Paraguayan" },
  { label: "Peru", value: "Peru", code: "51", nationality: "Peruvian" },
  { label: "Philippines", value: "Philippines", code: "63", nationality: "Filipino" },
  { label: "Poland", value: "Poland", code: "48", nationality: "Polish" },
  { label: "Portugal", value: "Portugal", code: "351", nationality: "Portuguese" },
  { label: "Qatar", value: "Qatar", code: "974", nationality: "Qatari" },
  { label: "Romania", value: "Romania", code: "40", nationality: "Romanian" },
  { label: "Russia", value: "Russia", code: "7", nationality: "Russian" },
  { label: "Rwanda", value: "Rwanda", code: "250", nationality: "Rwandan" },
  { label: "Saudi Arabia", value: "Saudi Arabia", code: "966", nationality: "Saudi" },
  { label: "Senegal", value: "Senegal", code: "221", nationality: "Senegalese" },
  { label: "Serbia", value: "Serbia", code: "381", nationality: "Serbian" },
  { label: "Singapore", value: "Singapore", code: "65", nationality: "Singaporean" },
  { label: "Slovakia", value: "Slovakia", code: "421", nationality: "Slovak" },
  { label: "Slovenia", value: "Slovenia", code: "386", nationality: "Slovenian" },
  { label: "Somalia", value: "Somalia", code: "252", nationality: "Somali" },
  { label: "South Africa", value: "South Africa", code: "27", nationality: "South African" },
  { label: "South Korea", value: "South Korea", code: "82", nationality: "South Korean" },
  { label: "Spain", value: "Spain", code: "34", nationality: "Spanish" },
  { label: "Sri Lanka", value: "Sri Lanka", code: "94", nationality: "Sri Lankan" },
  { label: "Sudan", value: "Sudan", code: "249", nationality: "Sudanese" },
  { label: "Sweden", value: "Sweden", code: "46", nationality: "Swedish" },
  { label: "Switzerland", value: "Switzerland", code: "41", nationality: "Swiss" },
  { label: "Syria", value: "Syria", code: "963", nationality: "Syrian" },
  { label: "Taiwan", value: "Taiwan", code: "886", nationality: "Taiwanese" },
  { label: "Tajikistan", value: "Tajikistan", code: "992", nationality: "Tajik" },
  { label: "Tanzania", value: "Tanzania", code: "255", nationality: "Tanzanian" },
  { label: "Thailand", value: "Thailand", code: "66", nationality: "Thai" },
  { label: "Tunisia", value: "Tunisia", code: "216", nationality: "Tunisian" },
  { label: "Turkey", value: "Turkey", code: "90", nationality: "Turkish" },
  { label: "Uganda", value: "Uganda", code: "256", nationality: "Ugandan" },
  { label: "Ukraine", value: "Ukraine", code: "380", nationality: "Ukrainian" },
  { label: "United Arab Emirates", value: "United Arab Emirates", code: "971", nationality: "Emirati" },
  { label: "United Kingdom", value: "United Kingdom", code: "44", nationality: "British" },
  { label: "United States", value: "United States", code: "1", nationality: "American" },
  { label: "Uruguay", value: "Uruguay", code: "598", nationality: "Uruguayan" },
  { label: "Uzbekistan", value: "Uzbekistan", code: "998", nationality: "Uzbek" },
  { label: "Venezuela", value: "Venezuela", code: "58", nationality: "Venezuelan" },
  { label: "Vietnam", value: "Vietnam", code: "84", nationality: "Vietnamese" },
  { label: "Yemen", value: "Yemen", code: "967", nationality: "Yemeni" },
  { label: "Zambia", value: "Zambia", code: "260", nationality: "Zambian" },
  { label: "Zimbabwe", value: "Zimbabwe", code: "263", nationality: "Zimbabwean" },
];

// Nationality (demonym) options, derived from countriesData. Deduplicated in
// case two countries share a demonym (e.g. "Congolese").
export const nationalitiesData = (() => {
  const seen = new Set();
  const list = [];
  for (const c of countriesData) {
    if (!c.nationality || seen.has(c.nationality)) continue;
    seen.add(c.nationality);
    list.push({ label: c.nationality, value: c.nationality, country: c.value });
  }
  return list.sort((a, b) => a.label.localeCompare(b.label));
})();
