export const countriesData = [
  { label: "Afghanistan", value: "Afghanistan", code: "93" },
  { label: "Albania", value: "Albania", code: "355" },
  { label: "Algeria", value: "Algeria", code: "213" },
  { label: "Andorra", value: "Andorra", code: "376" },
  { label: "Angola", value: "Angola", code: "244" },
  { label: "Argentina", value: "Argentina", code: "54" },
  { label: "Armenia", value: "Armenia", code: "374" },
  { label: "Australia", value: "Australia", code: "61" },
  { label: "Austria", value: "Austria", code: "43" },
  { label: "Azerbaijan", value: "Azerbaijan", code: "994" },
  { label: "Bahamas", value: "Bahamas", code: "1-242" },
  { label: "Bahrain", value: "Bahrain", code: "973" },
  { label: "Bangladesh", value: "Bangladesh", code: "880" },
  { label: "Barbados", value: "Barbados", code: "1-246" },
  { label: "Belarus", value: "Belarus", code: "375" },
  { label: "Belgium", value: "Belgium", code: "32" },
  { label: "Belize", value: "Belize", code: "501" },
  { label: "Benin", value: "Benin", code: "229" },
  { label: "Bhutan", value: "Bhutan", code: "975" },
  { label: "Bolivia", value: "Bolivia", code: "591" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina", code: "387" },
  { label: "Botswana", value: "Botswana", code: "267" },
  { label: "Brazil", value: "Brazil", code: "55" },
  { label: "Brunei", value: "Brunei", code: "673" },
  { label: "Bulgaria", value: "Bulgaria", code: "359" },
  { label: "Burkina Faso", value: "Burkina Faso", code: "226" },
  { label: "Burundi", value: "Burundi", code: "257" },
  { label: "Cambodia", value: "Cambodia", code: "855" },
  { label: "Cameroon", value: "Cameroon", code: "237" },
  { label: "Canada", value: "Canada", code: "1" },
  { label: "Cape Verde", value: "Cape Verde", code: "238" },
  { label: "Central African Republic", value: "Central African Republic", code: "236" },
  { label: "Chad", value: "Chad", code: "235" },
  { label: "Chile", value: "Chile", code: "56" },
  { label: "China", value: "China", code: "86" },
  { label: "Colombia", value: "Colombia", code: "57" },
  { label: "Comoros", value: "Comoros", code: "269" },
  { label: "Costa Rica", value: "Costa Rica", code: "506" },
  { label: "Croatia", value: "Croatia", code: "385" },
  { label: "Cuba", value: "Cuba", code: "53" },
  { label: "Cyprus", value: "Cyprus", code: "357" },
  { label: "Czech Republic", value: "Czech Republic", code: "420" },
  { label: "Denmark", value: "Denmark", code: "45" },
  { label: "Djibouti", value: "Djibouti", code: "253" },
  { label: "Dominican Republic", value: "Dominican Republic", code: "1-809" },
  { label: "DR Congo", value: "DR Congo", code: "243" },
  { label: "Ecuador", value: "Ecuador", code: "593" },
  { label: "Egypt", value: "Egypt", code: "20" },
  { label: "El Salvador", value: "El Salvador", code: "503" },
  { label: "Estonia", value: "Estonia", code: "372" },
  { label: "Ethiopia", value: "Ethiopia", code: "251" },
  { label: "Fiji", value: "Fiji", code: "679" },
  { label: "Finland", value: "Finland", code: "358" },
  { label: "France", value: "France", code: "33" },
  { label: "Gabon", value: "Gabon", code: "241" },
  { label: "Gambia", value: "Gambia", code: "220" },
  { label: "Georgia", value: "Georgia", code: "995" },
  { label: "Germany", value: "Germany", code: "49" },
  { label: "Ghana", value: "Ghana", code: "233" },
  { label: "Greece", value: "Greece", code: "30" },
  { label: "Guatemala", value: "Guatemala", code: "502" },
  { label: "Haiti", value: "Haiti", code: "509" },
  { label: "Honduras", value: "Honduras", code: "504" },
  { label: "Hong Kong", value: "Hong Kong", code: "852" },
  { label: "Hungary", value: "Hungary", code: "36" },
  { label: "Iceland", value: "Iceland", code: "354" },
  { label: "India", value: "India", code: "91" },
  { label: "Indonesia", value: "Indonesia", code: "62" },
  { label: "Iran", value: "Iran", code: "98" },
  { label: "Iraq", value: "Iraq", code: "964" },
  { label: "Ireland", value: "Ireland", code: "353" },
  { label: "Israel", value: "Israel", code: "972" },
  { label: "Italy", value: "Italy", code: "39" },
  { label: "Japan", value: "Japan", code: "81" },
  { label: "Jordan", value: "Jordan", code: "962" },
  { label: "Kazakhstan", value: "Kazakhstan", code: "7" },
  { label: "Kenya", value: "Kenya", code: "254" },
  { label: "Kuwait", value: "Kuwait", code: "965" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan", code: "996" },
  { label: "Laos", value: "Laos", code: "856" },
  { label: "Latvia", value: "Latvia", code: "371" },
  { label: "Lebanon", value: "Lebanon", code: "961" },
  { label: "Liberia", value: "Liberia", code: "231" },
  { label: "Libya", value: "Libya", code: "218" },
  { label: "Lithuania", value: "Lithuania", code: "370" },
  { label: "Luxembourg", value: "Luxembourg", code: "352" },
  { label: "Madagascar", value: "Madagascar", code: "261" },
  { label: "Malaysia", value: "Malaysia", code: "60" },
  { label: "Maldives", value: "Maldives", code: "960" },
  { label: "Mali", value: "Mali", code: "223" },
  { label: "Malta", value: "Malta", code: "356" },
  { label: "Mauritius", value: "Mauritius", code: "230" },
  { label: "Mexico", value: "Mexico", code: "52" },
  { label: "Moldova", value: "Moldova", code: "373" },
  { label: "Mongolia", value: "Mongolia", code: "976" },
  { label: "Montenegro", value: "Montenegro", code: "382" },
  { label: "Morocco", value: "Morocco", code: "212" },
  { label: "Myanmar", value: "Myanmar", code: "95" },
  { label: "Nepal", value: "Nepal", code: "977" },
  { label: "Netherlands", value: "Netherlands", code: "31" },
  { label: "New Zealand", value: "New Zealand", code: "64" },
  { label: "Nicaragua", value: "Nicaragua", code: "505" },
  { label: "Niger", value: "Niger", code: "227" },
  { label: "Nigeria", value: "Nigeria", code: "234" },
  { label: "North Korea", value: "North Korea", code: "850" },
  { label: "Norway", value: "Norway", code: "47" },
  { label: "Oman", value: "Oman", code: "968" },
  { label: "Pakistan", value: "Pakistan", code: "92" },
  { label: "Panama", value: "Panama", code: "507" },
  { label: "Paraguay", value: "Paraguay", code: "595" },
  { label: "Peru", value: "Peru", code: "51" },
  { label: "Philippines", value: "Philippines", code: "63" },
  { label: "Poland", value: "Poland", code: "48" },
  { label: "Portugal", value: "Portugal", code: "351" },
  { label: "Qatar", value: "Qatar", code: "974" },
  { label: "Romania", value: "Romania", code: "40" },
  { label: "Russia", value: "Russia", code: "7" },
  { label: "Rwanda", value: "Rwanda", code: "250" },
  { label: "Saudi Arabia", value: "Saudi Arabia", code: "966" },
  { label: "Senegal", value: "Senegal", code: "221" },
  { label: "Serbia", value: "Serbia", code: "381" },
  { label: "Singapore", value: "Singapore", code: "65" },
  { label: "Slovakia", value: "Slovakia", code: "421" },
  { label: "Slovenia", value: "Slovenia", code: "386" },
  { label: "Somalia", value: "Somalia", code: "252" },
  { label: "South Africa", value: "South Africa", code: "27" },
  { label: "South Korea", value: "South Korea", code: "82" },
  { label: "Spain", value: "Spain", code: "34" },
  { label: "Sri Lanka", value: "Sri Lanka", code: "94" },
  { label: "Sudan", value: "Sudan", code: "249" },
  { label: "Sweden", value: "Sweden", code: "46" },
  { label: "Switzerland", value: "Switzerland", code: "41" },
  { label: "Syria", value: "Syria", code: "963" },
  { label: "Taiwan", value: "Taiwan", code: "886" },
  { label: "Tajikistan", value: "Tajikistan", code: "992" },
  { label: "Tanzania", value: "Tanzania", code: "255" },
  { label: "Thailand", value: "Thailand", code: "66" },
  { label: "Tunisia", value: "Tunisia", code: "216" },
  { label: "Turkey", value: "Turkey", code: "90" },
  { label: "Uganda", value: "Uganda", code: "256" },
  { label: "Ukraine", value: "Ukraine", code: "380" },
  { label: "United Arab Emirates", value: "United Arab Emirates", code: "971" },
  { label: "United Kingdom", value: "United Kingdom", code: "44" },
  { label: "United States", value: "United States", code: "1" },
  { label: "Uruguay", value: "Uruguay", code: "598" },
  { label: "Uzbekistan", value: "Uzbekistan", code: "998" },
  { label: "Venezuela", value: "Venezuela", code: "58" },
  { label: "Vietnam", value: "Vietnam", code: "84" },
  { label: "Yemen", value: "Yemen", code: "967" },
  { label: "Zambia", value: "Zambia", code: "260" },
  { label: "Zimbabwe", value: "Zimbabwe", code: "263" },
];
