

export const properties = [
  {
    id: "prop-001",
    address: "42 Collins Street",
    suburb: "Melbourne",
    state: "VIC",
    postcode: "3000",
    price: 1250000,
    type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    landSize: 0,
    status: "listed",
    agent: "Sarah Mitchell",
    listingDate: "2024-12-15",
    image: "/modern-apartment-building-melbourne.jpg",
  },
  {
    id: "prop-002",
    address: "18 Beach Road",
    suburb: "Brighton",
    state: "VIC",
    postcode: "3186",
    price: 3450000,
    type: "house",
    bedrooms: 5,
    bathrooms: 3,
    parking: 2,
    landSize: 650,
    status: "under-contract",
    agent: "James Chen",
    listingDate: "2024-11-28",
    image: "/luxury-beach-house-brighton.jpg",
  },
  {
    id: "prop-003",
    address: "7/125 Pitt Street",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    price: 890000,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    landSize: 0,
    status: "settlement",
    agent: "Emma Wilson",
    listingDate: "2024-10-05",
    image: "/sydney-city-apartment.jpg",
  },
  {
    id: "prop-004",
    address: "156 Main Street",
    suburb: "Southbank",
    state: "VIC",
    postcode: "3006",
    price: 725000,
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    landSize: 0,
    status: "listed",
    agent: "Sarah Mitchell",
    listingDate: "2024-12-20",
    image: "/southbank-apartment-river-view.jpg",
  },
  {
    id: "prop-005",
    address: "89 Pacific Highway",
    suburb: "Crows Nest",
    state: "NSW",
    postcode: "2065",
    price: 2100000,
    type: "house",
    bedrooms: 4,
    bathrooms: 2,
    parking: 2,
    landSize: 420,
    status: "sold",
    agent: "Michael Park",
    listingDate: "2024-09-12",
    image: "/sydney-north-shore-house.jpg",
  },
]

export const matters = [
  {
    id: "MAT-2024-001",
    propertyAddress: "42 Collins Street, Melbourne VIC 3000",
    client: "Robert Thompson",
    clientEmail: "r.thompson@email.com",
    type: "purchase",
    status: "active",
    settlementDate: "2025-01-28",
    purchasePrice: 1250000,
    conveyancer: "Jennifer Blake",
    created: "2024-12-15",
    progress: 65,
    tasks: [
      { id: "t1", name: "Contract Review", status: "completed", dueDate: "2024-12-18" },
      { id: "t2", name: "Title Search", status: "completed", dueDate: "2024-12-20" },
      { id: "t3", name: "Finance Approval", status: "completed", dueDate: "2024-12-22" },
      { id: "t4", name: "Building Inspection", status: "in-progress", dueDate: "2025-01-05" },
      { id: "t5", name: "Settlement Preparation", status: "pending", dueDate: "2025-01-25" },
      { id: "t6", name: "Final Settlement", status: "pending", dueDate: "2025-01-28" },
    ],
  },
  {
    id: "MAT-2024-002",
    propertyAddress: "18 Beach Road, Brighton VIC 3186",
    client: "Amanda Foster",
    clientEmail: "a.foster@email.com",
    type: "sale",
    status: "pending",
    settlementDate: "2025-02-15",
    purchasePrice: 3450000,
    conveyancer: "David Liu",
    created: "2024-11-28",
    progress: 35,
    tasks: [
      { id: "t1", name: "Contract Preparation", status: "completed", dueDate: "2024-12-01" },
      { id: "t2", name: "Vendor Statement", status: "completed", dueDate: "2024-12-05" },
      { id: "t3", name: "Exchange of Contracts", status: "in-progress", dueDate: "2024-12-28" },
      { id: "t4", name: "Discharge of Mortgage", status: "pending", dueDate: "2025-02-10" },
      { id: "t5", name: "Final Settlement", status: "pending", dueDate: "2025-02-15" },
    ],
  },
  {
    id: "MAT-2024-003",
    propertyAddress: "7/125 Pitt Street, Sydney NSW 2000",
    client: "Chen Wei",
    clientEmail: "c.wei@email.com",
    type: "purchase",
    status: "settled",
    settlementDate: "2024-12-20",
    purchasePrice: 890000,
    conveyancer: "Jennifer Blake",
    created: "2024-10-05",
    progress: 100,
    tasks: [
      { id: "t1", name: "Contract Review", status: "completed", dueDate: "2024-10-10" },
      { id: "t2", name: "Title Search", status: "completed", dueDate: "2024-10-15" },
      { id: "t3", name: "Finance Approval", status: "completed", dueDate: "2024-10-25" },
      { id: "t4", name: "Settlement Preparation", status: "completed", dueDate: "2024-12-15" },
      { id: "t5", name: "Final Settlement", status: "completed", dueDate: "2024-12-20" },
    ],
  },
]

export const complianceCases = [
  {
    id: "COMP-001",
    client: "Robert Thompson",
    type: "KYC",
    status: "approved",
    riskLevel: "low",
    assignedTo: "Compliance Team A",
    created: "2024-12-15",
    lastUpdated: "2024-12-16",
  },
  {
    id: "COMP-002",
    client: "Amanda Foster",
    type: "AML",
    status: "pending",
    riskLevel: "medium",
    assignedTo: "Compliance Team B",
    created: "2024-11-28",
    lastUpdated: "2024-12-20",
  },
  {
    id: "COMP-003",
    client: "Chen Wei",
    type: "PEP",
    status: "flagged",
    riskLevel: "high",
    assignedTo: "Senior Compliance",
    created: "2024-10-05",
    lastUpdated: "2024-12-22",
  },
  {
    id: "COMP-004",
    client: "Sarah Johnson",
    type: "Sanctions",
    status: "approved",
    riskLevel: "low",
    assignedTo: "Compliance Team A",
    created: "2024-12-10",
    lastUpdated: "2024-12-12",
  },
  {
    id: "COMP-005",
    client: "Michael Park",
    type: "KYC",
    status: "rejected",
    riskLevel: "high",
    assignedTo: "Senior Compliance",
    created: "2024-12-01",
    lastUpdated: "2024-12-18",
  },
]

export const documents = [
  {
    id: "doc-001",
    name: "Contract of Sale - 42 Collins St",
    type: "contract",
    status: "signed",
    uploadedBy: "Jennifer Blake",
    uploadedAt: "2024-12-15",
    size: "2.4 MB",
  },
  {
    id: "doc-002",
    name: "Title Search Report",
    type: "title",
    status: "verified",
    uploadedBy: "System",
    uploadedAt: "2024-12-16",
    size: "1.2 MB",
  },
  {
    id: "doc-003",
    name: "Building Inspection Report",
    type: "search",
    status: "pending",
    uploadedBy: "Robert Thompson",
    uploadedAt: "2024-12-22",
    size: "5.8 MB",
  },
  {
    id: "doc-004",
    name: "Passport - R. Thompson",
    type: "identity",
    status: "verified",
    uploadedBy: "Robert Thompson",
    uploadedAt: "2024-12-15",
    size: "850 KB",
  },
  {
    id: "doc-005",
    name: "Bank Statement - Dec 2024",
    type: "financial",
    status: "pending",
    uploadedBy: "Robert Thompson",
    uploadedAt: "2024-12-23",
    size: "340 KB",
  },
]

export const trustAccount = {
  id: "trust-001",
  accountName: "DOOIT.AI Trust Account",
  balance: 4589750.0,
  transactions: [
    {
      id: "tx-001",
      date: "2024-12-23",
      description: "Deposit - Thompson Purchase",
      amount: 125000,
      type: "credit",
      reference: "MAT-2024-001",
    },
    {
      id: "tx-002",
      date: "2024-12-22",
      description: "Settlement - Chen Wei",
      amount: 890000,
      type: "debit",
      reference: "MAT-2024-003",
    },
    {
      id: "tx-003",
      date: "2024-12-20",
      description: "Deposit - Foster Sale",
      amount: 345000,
      type: "credit",
      reference: "MAT-2024-002",
    },
    {
      id: "tx-004",
      date: "2024-12-18",
      description: "Stamp Duty Payment",
      amount: 45000,
      type: "debit",
      reference: "MAT-2024-003",
    },
    {
      id: "tx-005",
      date: "2024-12-15",
      description: "Legal Fees - Chen Wei",
      amount: 3500,
      type: "debit",
      reference: "MAT-2024-003",
    },
  ],
}

export const dashboardStats = {
  totalMatters: 24,
  activeMatters: 8,
  pendingSettlements: 5,
  completedThisMonth: 11,
  totalPropertyValue: 45750000,
  complianceRate: 94.2,
  documentsProcessed: 156,
  clientSatisfaction: 4.8,
}
