// Sample TBML/OSINT report response, shaped exactly like the API payload
// (see response_tbml_1.json). Used as the default report until this view is
// wired up to a live endpoint.
const mockTbmlReportData = {
  report_id: "TBML-DDF975C066E1",
  db_source: 1,
  environment: "production",
  status: "COMPLETED",
  created_at: "2026-08-22T08:21:11.755302Z",
  completed_at: "2026-08-22T08:21:11.755553Z",
  document_extracts: [
    {
      document_type: "Invoice",
      document_number: "123456",
      document_date: "May 10, 2006",
      lc_number: null,
      page_number: 1,
      exporter: {
        name: "Supplier Street Address",
        address: "City, State ZIP",
        country: null,
        swift_code: null,
        iban: null,
        bank_name: null,
        tax_id: null,
        phone: "000.000.0000",
        email: null,
      },
      importer: {
        name: "Intel Corporation",
        address: "P.O. Box 1000 Hillsboro, OR 97123-1000",
        country: null,
        swift_code: null,
        iban: null,
        bank_name: null,
        tax_id: null,
        phone: null,
        email: null,
      },
      notify_party: {
        name: "Intel Corporation",
        address: "3601 Juliette Lane Santa Clara, CA 95052",
        country: null,
        swift_code: null,
        iban: null,
        bank_name: null,
        tax_id: null,
        phone: null,
        email: null,
      },
      issuing_bank: {
        name: null,
        address: null,
        country: null,
        swift_code: null,
        iban: null,
        bank_name: null,
        tax_id: null,
        phone: null,
        email: null,
      },
      beneficiary_bank: {
        name: null,
        address: null,
        country: null,
        swift_code: null,
        iban: null,
        bank_name: null,
        tax_id: null,
        phone: null,
        email: null,
      },
      incoterms: null,
      port_of_loading: null,
      port_of_discharge: null,
      shipping_method: "UPS",
      container_number: null,
      vessel_flight: null,
      payment_terms: "2%15 Days, Net 45",
      sales_terms: null,
      subtotal: "8500.00",
      freight_charges: null,
      insurance: null,
      total_amount: "8623.75",
      currency: null,
      amount_in_words: null,
      fob_value: null,
      cif_value: null,
      products: [
        {
          line_number: 1,
          description:
            "Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color",
          hs_code: null,
          quantity: null,
          unit: null,
          unit_price: "7000.00",
          total_price: "7000.00",
          currency: null,
          country_of_origin: null,
          weight_net: null,
          weight_gross: null,
        },
        {
          line_number: 2,
          description: "Material - Paint",
          hs_code: null,
          quantity: null,
          unit: null,
          unit_price: "1500.00",
          total_price: "1500.00",
          currency: null,
          country_of_origin: null,
          weight_net: null,
          weight_gross: null,
        },
      ],
      raw_text:
        "Invoice\n(Example Only)\nINVOICE NO: 123456\nDATE: May 10, 2006\nSupplier Street Address\nCity, State ZIP\n000.000.0000 Fax 000.000.0000\nShip To:\nIntel Corporation\n3601 Juliette Lane\nSanta Clara, CA 95052\nBill To:\nIntel Corporation\nP.O. Box 1000\nHillsboro, OR 97123-1000\nSALESPERSON\nP.O. NUMBER\nDATE SHIPPED\nSHIPPED VIA\nF.O.B. POINT\nTERMS\nCAC038793000\nUPS\n2%15 Days, Net 45\nQUANTITY\nLINE\nRELEASE/DELIVERY\nDESCRIPTION\nINTEL P/N\nUNIT PRICE\nAMOUNT\n001\nLabor- Paint the risers and stringers\non all five stairways in RNB with\npaint to match color\n7000.00\n7000.00\n002\nMaterial - Paint\n1500.00\n1500.00\nSUBTOTAL\n8500.00\nSALES TAX\n123.75\nSHIPPING & HANDLING\n0.00\nTOTAL DUE\n8623.75\nImportant Tips to Remember When Invoicing Intel\nSupplier name and remittance address must be the same as referenced on the Purchase Order. If there has been a change or\nthe information on the Purchase Order is incorrect, contact the buyer prior to invoicing to prevent payment delays.\nThe word 'invoice' must be on the invoice. The invoice number must be unique (not the same as prior invoices for that supplier),\nor it will be returned unpaid.\nUse exactly the same 'Ship To' address referenced on the Purchase Order.\nSubmit invoices to the same 'Bill To' address shown on the Purchase Order. Note: Intel has multiple 'bill-to' addresses.\nPlease verify that the invoice 'bill-to' address matches the Purchase Order perfectly to prevent payment delays.\nInvoice must reference the full Purchase Order number as referenced on the Purchase Order, including all zeros. Purchase order\nnumbers are at least nine characters long, beginning with two or more alpha characters followed by numeric and/or alpha\ncharacters. If there is a release number involved, it must also be referenced on the invoice.",
    },
  ],
  osint_results: [
    {
      product_key: "labor_paint_the_risers_and_stringers",
      product_description:
        "Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color",
      hs_code: null,
      data_availability: "SUFFICIENT",
      availability_note: "Market range established from 9 comparable observation(s).",
      reference_price_low: "USD 700.00 per for 20riser project",
      reference_price_high: "USD 1,350.00 per for 20riser project",
      reference_price_mid: "USD 1,000.00 per for 20riser project",
      reference_price_currency: "USD",
      reference_price_unit: "for 20riser project",
      price_observation_count: 28,
      price_sources: ["www.homeadvisor.com", "latestcost.com"],
      typical_origin_countries: [],
      typical_trade_routes: [],
      sanctioned_jurisdiction_flag: false,
      hs_codes_observed: [],
      aggregated_findings:
        "[www.homeadvisor.com] Keep in mind that detailed painting of railings and balusters can cost up to $20 per linear foot due to the intricate work involved.\n\n[latestcost.com] Labor is typically the largest cost element for stair riser painting. A small project with 10â15 risers can take 1â2 days; larger jobs may extend to 2â3 days.",
      aggregated_ocr:
        "[www.homeadvisor.com] Keep in mind that detailed painting of railings and balusters can cost up to $20 per linear foot due to the intricate work involved.\n\n[latestcost.com] Labor is typically the largest cost element for stair riser painting. A small project with 10â15 risers can take 1â2 days; larger jobs may extend to 2â3 days.",
    },
    {
      product_key: "material_paint",
      product_description: "Material - Paint",
      hs_code: null,
      data_availability: "SUFFICIENT",
      availability_note: "Market range established from 2 comparable observation(s).",
      reference_price_low: "USD 12.00 per litre",
      reference_price_high: "USD 25.00 per litre",
      reference_price_mid: "USD 18.50 per litre",
      reference_price_currency: "USD",
      reference_price_unit: "litre",
      price_observation_count: 2,
      price_sources: ["procalclab.com"],
      typical_origin_countries: [],
      typical_trade_routes: [],
      sanctioned_jurisdiction_flag: false,
      hs_codes_observed: [],
      aggregated_findings:
        "[www.facebook.com] Is $25k labor and material a fair price to paint a 6 unit complex in Texas?\n\n[www.facebook.com] Always price your paint and materials first then have a panel price\n\n[procalclab.com] Note: Calculations are approximate. Actual material use and costs depend on application method, surface condition and local prices.",
      aggregated_ocr:
        "[www.facebook.com] Is $25k labor and material a fair price to paint a 6 unit complex in Texas?\n\n[www.facebook.com] Always price your paint and materials first then have a panel price\n\n[procalclab.com] Note: Calculations are approximate. Actual material use and costs depend on application method, surface condition and local prices.",
    },
  ],
  product_analyses: [
    {
      product_description:
        "Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color",
      hs_code: "null",
      declared_unit_price: "7000.00",
      reference_price_range: "USD 700.00 - USD 1,350.00 per for 20riser project",
      price_deviation_pct: null,
      data_availability: "SUFFICIENT",
      findings: [
        {
          indicator: "PRICE_ANOMALY",
          severity: "HIGH",
          description:
            "The declared price for labor is significantly higher than the established market range for comparable painting projects. While the units of comparison are not perfectly aligned (declared as a total for 'five stairways' versus market data 'per for 20riser project'), the magnitude of the difference is substantial.",
          evidence:
            "Declared price: $7,000.00. Market price range for a '20riser project': $700.00 - $1,350.00. The declared price is over five times the high end of the market range for a '20riser project'.",
          recommendation:
            "Investigate the justification for the declared labor cost, requesting detailed breakdown of hours, rates, and scope of work for the 'five stairways' project to compare against market benchmarks more precisely. Seek clarification on how 'five stairways' translates to 'risers' for a direct comparison.",
        },
        {
          indicator: "DOCUMENT_INCONSISTENCY",
          severity: "LOW",
          description: "The currency for the declared unit price is not specified on the invoice.",
          evidence: "Invoice line item 'unit_price' is '7000.00' with no currency indicated.",
          recommendation: "Request clarification on the currency used for the transaction.",
        },
      ],
      risk_level: "HIGH",
      risk_score: 75,
      summary:
        "The declared price for labor is substantially higher than market rates for comparable projects, indicating a potential over-invoicing risk. The currency for the declared price is also missing.",
    },
    {
      product_description: "Material - Paint",
      hs_code: "null",
      declared_unit_price: "1500.00",
      reference_price_range: "USD 12.00 - USD 25.00 per litre",
      price_deviation_pct: null,
      data_availability: "SUFFICIENT",
      findings: [
        {
          indicator: "DOCUMENT_INCONSISTENCY",
          severity: "LOW",
          description: "The currency for the declared unit price is not specified on the invoice.",
          evidence: "Invoice line item 'unit_price' is '1500.00' with no currency indicated.",
          recommendation: "Request clarification on the currency used for the transaction.",
        },
      ],
      risk_level: "INSUFFICIENT_DATA",
      risk_score: 0,
      summary:
        "No quantity for 'Material - Paint' is provided on the invoice, preventing a direct price comparison against the market reference price per litre. The declared price could not be tested. The currency for the declared price is also missing.",
    },
  ],
  overall_risk_level: "HIGH",
  overall_risk_score: 70,
  overall_risk_summary:
    "The transaction presents a HIGH overall risk primarily due to a significant price anomaly identified for the 'Labor' component, where the declared price is substantially above market rates for comparable services. Several document inconsistencies, including missing currency information and a discrepancy in the total amount, further contribute to the elevated risk profile. The 'Material - Paint' component could not be price-tested due to insufficient data on the invoice.",
  tbml_indicators_detected: ["PRICE_ANOMALY", "DOCUMENT_INCONSISTENCY"],
  requires_analyst_review: true,
  review_reasons: ["An overall risk of HIGH requires analyst confirmation before any action is taken."],
  narrative_report:
    "## Executive Summary\nThis trade transaction involves the provision of painting labor and materials. A significant price anomaly has been identified for the labor component, where the declared price of $7,000.00 is substantially higher than market rates for comparable projects. Several document inconsistencies, including missing currency details for product prices and a discrepancy in the invoice total, further elevate the risk. The 'Material - Paint' component could not be price-tested due to a lack of quantity information on the invoice. The overall risk level for this transaction is assessed as HIGH.\n\n## Trade Transaction Overview\nThis transaction is documented by an Invoice (Number: 123456, Date: May 10, 2006). The exporter is 'Supplier Street Address' and the importer is 'Intel Corporation'. The invoice details two line items: 'Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color' for $7,000.00, and 'Material - Paint' for $1,500.00. The subtotal is $8,500.00, and the total amount is $8,623.75. The shipping method is stated as UPS, and payment terms are '2%15 Days, Net 45'.\n\n## Product Analysis\n**Product 1: Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color**\n*   Declared Unit Price: $7,000.00 (implied total for the labor item)\n*   HS Code: Not provided\n*   Findings: A significant price anomaly was detected, with the declared price being substantially higher than market benchmarks. The currency for this price was not specified on the invoice.\n\n**Product 2: Material - Paint**\n*   Declared Unit Price: $1,500.00 (implied total for the material item)\n*   HS Code: Not provided\n*   Findings: No quantity for the paint material was provided on the invoice, preventing a meaningful price comparison. The currency for this price was not specified on the invoice.\n\n## Market Research Findings\n**Product 1: Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color**\nMarket research located a price range for comparable painting projects. Published sources indicate that a '20riser project' typically costs between USD 700.00 and USD 1,350.00. This range was established from 28 independent observations.\n\n**Product 2: Material - Paint**\nMarket research located a price range for paint materials. Published sources indicate a price range of USD 12.00 to USD 25.00 per litre. This range was established from 2 independent observations.\n\n## TBML Risk Indicators\n*   **PRICE_ANOMALY (HIGH Severity):** The declared price for labor is significantly above the market reference range for comparable projects.\n*   **DOCUMENT_INCONSISTENCY (MEDIUM Severity):** Missing country information for both exporter and importer. Missing currency for product prices and total amount. Discrepancy between subtotal and total amount on the invoice.\n\n## Price Analysis\n**Product 1: Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color**\nThe declared price for this labor item is $7,000.00. Market research indicates a price range of USD 700.00 to USD 1,350.00 for a '20riser project'. While the invoice describes 'all five stairways' and does not specify the number of risers, the declared price of $7,000.00 is over five times the upper bound of the market range for a '20riser project'. This represents a substantial deviation, suggesting potential over-invoicing. Due to the difference in units ('five stairways' vs. '20riser project'), a precise percentage deviation cannot be calculated, but the magnitude of the declared price compared to the market range for a similar scope of work is highly anomalous.\n\n**Product 2: Material - Paint**\nThe declared price for 'Material - Paint' is $1,500.00. Market research indicates a price range of USD 12.00 to USD 25.00 per litre. However, the invoice does not specify the quantity of paint (e.g., in litres) purchased. Without a declared quantity, it is not possible to compare the total declared price against the market unit price range, and therefore, no price deviation can be calculated or assessed.\n\n## Trade Route Analysis\nNo specific trade route details (port of loading/discharge, vessel/flight information) are provided on the invoice, which is consistent with a service and material supply transaction rather than a typical goods shipment. The shipping method is stated as UPS, but no further routing information is available for analysis.\n\n## Document Consistency Review\nSeveral inconsistencies were noted across the provided document:\n*   **Missing Country Information:** The exporter's and importer's addresses lack explicit country declarations.\n*   **Missing Currency:** The currency for the declared product prices and the overall total amount is not specified on the invoice.\n*   **Total Amount Discrepancy:** The subtotal is listed as $8,500.00, but the total amount is $8,623.75. No freight charges or insurance costs are itemized to account for the $123.75 difference.\n\n## Limitations\nMarket data for 'Labor- Paint the risers and stringers on all five stairways in RNB with paint to match color' provided a reference range in 'per for 20riser project' units, which did not perfectly align with the invoice's 'five stairways' description. While a significant price anomaly was identified, a precise percentage deviation could not be calculated due to this unit difference.\n\nFor 'Material - Paint', no quantity (e.g., litres) was specified on the invoice. Consequently, despite the availability of market reference prices per litre, the declared price for this product could not be tested for over-invoicing or under-invoicing, and no price deviation could be computed. This means the assessment for 'Material - Paint' is limited to document-only indicators.\n\n## Recommendations\n1.  **Request Detailed Breakdown for Labor:** Seek a detailed breakdown of the labor costs, including hours, rates, and a clear scope of work for the 'five stairways' to enable a more precise comparison with market benchmarks.\n2.  **Clarify Missing Information:** Request the explicit currency for all monetary values on the invoice (product prices, subtotal, total amount).\n3.  **Reconcile Total Amount:** Request an explanation for the $123.75 difference between the subtotal and the total amount, or an itemization of any additional charges.\n4.  **Obtain Material Quantity:** Request the quantity of 'Material - Paint' supplied to allow for a proper price comparison against market rates.\n5.  **Verify Party Details:** Request full country details for both the exporter and importer.\n\n## Conclusion\nThe transaction exhibits a HIGH risk profile primarily due to the substantial over-invoicing indicator for the labor component and multiple document inconsistencies. While the 'Material - Paint' component could not be fully assessed for price anomalies due to data limitations, the identified red flags warrant further investigation and clarification from the transacting parties to mitigate potential TBML risks.",
  methodology: {
    db_source: 1,
    environment: "production",
    search_provider: "searxng",
    pages_in_document: 1,
    documents_extracted: 1,
    products_detected: 2,
    queries_attempted: 24,
    queries_successful: 24,
    queries_blocked: 0,
    queries_errored: 0,
    results_seen: 342,
    urls_selected: 15,
    pages_read: 12,
    pages_failed: 3,
    pages_relevant: 5,
    price_observations: 30,
    domains_consulted: [
      "www.facebook.com",
      "github.com",
      "www.linkedin.com",
      "www.homeadvisor.com",
      "latestcost.com",
      "nlp.biu.ac.il",
      "www.scribd.com",
      "ofac.treasury.gov",
      "sanctionssearch.ofac.treas.gov",
      "www.linzalytics.com",
      "www.sigma360.com",
      "procalclab.com",
      "www.supplychainbrain.com",
      "www.livemint.com",
    ],
    products_with_price_data: 2,
    products_without_data: 0,
    limitations: [
      "The exporter's name and address ('Supplier Street Address', 'City, State ZIP') appear to be placeholders. Currency is not explicitly stated on the document for any monetary values, so it has been left empty as per instructions not to fabricate values. The quantity for line items 001 and 002 is not explicitly stated.",
    ],
    narrative_warnings: [],
    model_usage: {
      calls: 26,
      input_tokens: 31754,
      output_tokens: 9061,
      thought_tokens: 20236,
      grounded_search_queries: 0,
      models_used: ["gemini-2.5-flash"],
    },
    collected_at: "2026-08-22T08:17:25.447984Z",
  },
};

export default mockTbmlReportData;
