/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Nissa_v3.glb -T
Files: Nissa_v3.glb [3.65MB] > C:\Users\Uzair\Documents\New folder (2)\Nissa_v3-transformed.glb [784.88KB] (78%)
*/
"use client";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import React from "react";
import { SkeletonUtils } from "three-stdlib";

export default function Nissa_v3(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/Nissa_v3-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useFrame(() => {
    actions["Animation"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh
          name="Dress001"
          geometry={nodes.Dress001.geometry}
          material={materials.Abaya}
          skeleton={nodes.Dress001.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <group name="HeadSet002" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <skinnedMesh
            name="Cylinder008_Blue_02_0002"
            geometry={nodes.Cylinder008_Blue_02_0002.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cylinder008_Blue_02_0002.skeleton}
          />
          <skinnedMesh
            name="Cylinder008_Blue_02_0002_1"
            geometry={nodes.Cylinder008_Blue_02_0002_1.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cylinder008_Blue_02_0002_1.skeleton}
          />
          <skinnedMesh
            name="Cylinder008_Blue_02_0002_2"
            geometry={nodes.Cylinder008_Blue_02_0002_2.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cylinder008_Blue_02_0002_2.skeleton}
          />
          <skinnedMesh
            name="Cylinder008_Blue_02_0002_3"
            geometry={nodes.Cylinder008_Blue_02_0002_3.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cylinder008_Blue_02_0002_3.skeleton}
          />
          <skinnedMesh
            name="Cylinder008_Blue_02_0002_4"
            geometry={nodes.Cylinder008_Blue_02_0002_4.geometry}
            material={materials.PaletteMaterial002}
            skeleton={nodes.Cylinder008_Blue_02_0002_4.skeleton}
          />
        </group>
        <skinnedMesh
          name="Hijab001"
          geometry={nodes.Hijab001.geometry}
          material={materials.Scarf}
          skeleton={nodes.Hijab001.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <group name="Limbs001" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <skinnedMesh
            name="Mesh_1001"
            geometry={nodes.Mesh_1001.geometry}
            material={materials.Skin}
            skeleton={nodes.Mesh_1001.skeleton}
          />
          <skinnedMesh
            name="Mesh_1001_1"
            geometry={nodes.Mesh_1001_1.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Mesh_1001_1.skeleton}
          />
        </group>
        <skinnedMesh
          name="Wolf3D_Hair001"
          geometry={nodes.Wolf3D_Hair001.geometry}
          material={materials.Hair}
          skeleton={nodes.Wolf3D_Hair001.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <skinnedMesh
          name="EyeLeft001"
          geometry={nodes.EyeLeft001.geometry}
          material={materials["Brown_Eye.001"]}
          skeleton={nodes.EyeLeft001.skeleton}
          morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <skinnedMesh
          name="EyeRight001"
          geometry={nodes.EyeRight001.geometry}
          material={materials["Brown_Eye.001"]}
          skeleton={nodes.EyeRight001.skeleton}
          morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <skinnedMesh
          name="Wolf3D_Head002"
          geometry={nodes.Wolf3D_Head002.geometry}
          material={materials.Skin}
          skeleton={nodes.Wolf3D_Head002.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head002.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head002.morphTargetInfluences}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Nissa_v3-transformed.glb");
