

export const countries = [
  { id: "1", label: "🇦🇫 Afghanistan", value: "afghanistan" },
  { id: "2", label: "🇦🇱 Albania", value: "albania" },
  { id: "3", label: "🇩🇿 Algeria", value: "algeria" },
  { id: "4", label: "🇦🇸 American Samoa", value: "american_samoa" },
  { id: "5", label: "🇦🇩 Andorra", value: "andorra" },
  { id: "6", label: "🇦🇴 Angola", value: "angola" },
  { id: "7", label: "🇦🇮 Anguilla", value: "anguilla" },
  { id: "8", label: "🇦🇬 Antigua and Barbuda", value: "antigua_and_barbuda" },
  { id: "9", label: "🇦🇷 Argentina", value: "argentina" },
  { id: "10", label: "🇦🇲 Armenia", value: "armenia" },
  { id: "11", label: "🇦🇼 Aruba", value: "aruba" },
  { id: "12", label: "🇦🇺 Australia", value: "australia" },
  { id: "13", label: "🇦🇹 Austria", value: "austria" },
  { id: "14", label: "🇦🇿 Azerbaijan", value: "azerbaijan" },
  { id: "15", label: "🇧🇸 Bahamas", value: "bahamas" },
  { id: "16", label: "🇧🇭 Bahrain", value: "bahrain" },
  { id: "17", label: "🇧🇩 Bangladesh", value: "bangladesh" },
  { id: "18", label: "🇧🇧 Barbados", value: "barbados" },
  { id: "19", label: "🇧🇾 Belarus", value: "belarus" },
  { id: "20", label: "🇧🇪 Belgium", value: "belgium" },
  { id: "21", label: "🇧🇿 Belize", value: "belize" },
  { id: "22", label: "🇧🇯 Benin", value: "benin" },
  { id: "23", label: "🇧🇲 Bermuda", value: "bermuda" },
  { id: "24", label: "🇧🇹 Bhutan", value: "bhutan" },
  { id: "25", label: "🇧🇴 Bolivia", value: "bolivia" },
  { id: "26", label: "🇧🇦 Bosnia and Herzegovina", value: "bosnia_and_herzegovina" },
  { id: "27", label: "🇧🇼 Botswana", value: "botswana" },
  { id: "28", label: "🇧🇷 Brazil", value: "brazil" },
  { id: "29", label: "🇻🇬 British Virgin Islands", value: "british_virgin_islands" },
  { id: "30", label: "🇧🇳 Brunei Darussalam", value: "brunei_darussalam" },
  { id: "31", label: "🇧🇬 Bulgaria", value: "bulgaria" },
  { id: "32", label: "🇧🇫 Burkina Faso", value: "burkina_faso" },
  { id: "33", label: "🇧🇮 Burundi", value: "burundi" },
  { id: "34", label: "🇨🇻 Cabo Verde", value: "cabo_verde" },
  { id: "35", label: "🇰🇭 Cambodia", value: "cambodia" },
  { id: "36", label: "🇨🇲 Cameroon", value: "cameroon" },
  { id: "37", label: "🇨🇦 Canada", value: "canada" },
  { id: "38", label: "🇰🇾 Cayman Islands", value: "cayman_islands" },
  { id: "39", label: "🇨🇫 Central African Republic", value: "central_african_republic" },
  { id: "40", label: "🇹🇩 Chad", value: "chad" },
  { id: "41", label: "🇨🇱 Chile", value: "chile" },
  { id: "42", label: "🇨🇳 China", value: "china" },
  { id: "43", label: "🇨🇽 Christmas Island", value: "christmas_island" },
  { id: "44", label: "🇨🇴 Colombia", value: "colombia" },
  { id: "45", label: "🇰🇲 Comoros", value: "comoros" },
  { id: "46", label: "🇨🇬 Congo (Brazzaville)", value: "congo_brazzaville" },
  { id: "47", label: "🇨🇩 Congo (Kinshasa)", value: "congo_kinshasa" },
  { id: "48", label: "🇨🇰 Cook Islands", value: "cook_islands" },
  { id: "49", label: "🇨🇷 Costa Rica", value: "costa_rica" },
  { id: "50", label: "🇨🇮 Côte d'Ivoire", value: "cote_divoire" },
  { id: "51", label: "🇭🇷 Croatia", value: "croatia" },
  { id: "52", label: "🇨🇺 Cuba", value: "cuba" },
  { id: "53", label: "🇨🇾 Cyprus", value: "cyprus" },
  { id: "54", label: "🇨🇿 Czechia", value: "czechia" },
  { id: "55", label: "🇩🇰 Denmark", value: "denmark" },
  { id: "56", label: "🇩🇯 Djibouti", value: "djibouti" },
  { id: "57", label: "🇩🇲 Dominica", value: "dominica" },
  { id: "58", label: "🇩🇴 Dominican Republic", value: "dominican_republic" },
  { id: "59", label: "🇪🇨 Ecuador", value: "ecuador" },
  { id: "60", label: "🇪🇬 Egypt", value: "egypt" },
  { id: "61", label: "🇸🇻 El Salvador", value: "el_salvador" },
  { id: "62", label: "🇬🇶 Equatorial Guinea", value: "equatorial_guinea" },
  { id: "63", label: "🇪🇷 Eritrea", value: "eritrea" },
  { id: "64", label: "🇪🇪 Estonia", value: "estonia" },
  { id: "65", label: "🇸🇿 Eswatini", value: "eswatini" },
  { id: "66", label: "🇪🇹 Ethiopia", value: "ethiopia" },
  { id: "67", label: "🇫🇯 Fiji", value: "fiji" },
  { id: "68", label: "🇫🇮 Finland", value: "finland" },
  { id: "69", label: "🇫🇷 France", value: "france" },
  { id: "70", label: "🇬🇦 Gabon", value: "gabon" },
  { id: "71", label: "🇬🇲 Gambia", value: "gambia" },
  { id: "72", label: "🇬🇪 Georgia", value: "georgia" },
  { id: "73", label: "🇩🇪 Germany", value: "germany" },
  { id: "74", label: "🇬🇭 Ghana", value: "ghana" },
  { id: "75", label: "🇬🇮 Gibraltar", value: "gibraltar" },
  { id: "76", label: "🇬🇷 Greece", value: "greece" },
  { id: "77", label: "🇬🇩 Grenada", value: "grenada" },
  { id: "78", label: "🇬🇹 Guatemala", value: "guatemala" },
  { id: "79", label: "🇬🇳 Guinea", value: "guinea" },
  { id: "80", label: "🇬🇼 Guinea-Bissau", value: "guinea_bissau" },
  { id: "81", label: "🇬🇾 Guyana", value: "guyana" },
  { id: "82", label: "🇭🇹 Haiti", value: "haiti" },
  { id: "83", label: "🇭🇳 Honduras", value: "honduras" },
  { id: "84", label: "🇭🇰 Hong Kong", value: "hong_kong" },
  { id: "85", label: "🇭🇺 Hungary", value: "hungary" },
  { id: "86", label: "🇮🇸 Iceland", value: "iceland" },
  { id: "87", label: "🇮🇳 India", value: "india" },
  { id: "88", label: "🇮🇩 Indonesia", value: "indonesia" },
  { id: "89", label: "🇮🇷 Iran", value: "iran" },
  { id: "90", label: "🇮🇶 Iraq", value: "iraq" },
  { id: "91", label: "🇮🇪 Ireland", value: "ireland" },
  { id: "92", label: "🇮🇱 Israel", value: "israel" },
  { id: "93", label: "🇮🇹 Italy", value: "italy" },
  { id: "94", label: "🇯🇲 Jamaica", value: "jamaica" },
  { id: "95", label: "🇯🇵 Japan", value: "japan" },
  { id: "96", label: "🇯🇴 Jordan", value: "jordan" },
  { id: "97", label: "🇰🇿 Kazakhstan", value: "kazakhstan" },
  { id: "98", label: "🇰🇪 Kenya", value: "kenya" },
  { id: "99", label: "🇰🇮 Kiribati", value: "kiribati" },
  { id: "100", label: "🇽🇰 Kosovo", value: "kosovo" },
  { id: "101", label: "🇰🇼 Kuwait", value: "kuwait" },
  { id: "102", label: "🇰🇬 Kyrgyzstan", value: "kyrgyzstan" },
  { id: "103", label: "🇱🇦 Laos", value: "laos" },
  { id: "104", label: "🇱🇻 Latvia", value: "latvia" },
  { id: "105", label: "🇱🇧 Lebanon", value: "lebanon" },
  { id: "106", label: "🇱🇸 Lesotho", value: "lesotho" },
  { id: "107", label: "🇱🇷 Liberia", value: "liberia" },
  { id: "108", label: "🇱🇾 Libya", value: "libya" },
  { id: "109", label: "🇱🇮 Liechtenstein", value: "liechtenstein" },
  { id: "110", label: "🇱🇹 Lithuania", value: "lithuania" },
  { id: "111", label: "🇱🇺 Luxembourg", value: "luxembourg" },
  { id: "112", label: "🇲🇴 Macao", value: "macao" },
  { id: "113", label: "🇲🇬 Madagascar", value: "madagascar" },
  { id: "114", label: "🇲🇼 Malawi", value: "malawi" },
  { id: "115", label: "🇲🇾 Malaysia", value: "malaysia" },
  { id: "116", label: "🇲🇻 Maldives", value: "maldives" },
  { id: "117", label: "🇲🇱 Mali", value: "mali" },
  { id: "118", label: "🇲🇹 Malta", value: "malta" },
  { id: "119", label: "🇲🇭 Marshall Islands", value: "marshall_islands" },
  { id: "120", label: "🇲🇷 Mauritania", value: "mauritania" },
  { id: "121", label: "🇲🇺 Mauritius", value: "mauritius" },
  { id: "122", label: "🇲🇽 Mexico", value: "mexico" },
  { id: "123", label: "🇫🇲 Micronesia", value: "micronesia" },
  { id: "124", label: "🇲🇩 Moldova", value: "moldova" },
  { id: "125", label: "🇲🇨 Monaco", value: "monaco" },
  { id: "126", label: "🇲🇳 Mongolia", value: "mongolia" },
  { id: "127", label: "🇲🇪 Montenegro", value: "montenegro" },
  { id: "128", label: "🇲🇦 Morocco", value: "morocco" },
  { id: "129", label: "🇲🇿 Mozambique", value: "mozambique" },
  { id: "130", label: "🇲🇲 Myanmar", value: "myanmar" },
  { id: "131", label: "🇳🇦 Namibia", value: "namibia" },
  { id: "132", label: "🇳🇷 Nauru", value: "nauru" },
  { id: "133", label: "🇳🇵 Nepal", value: "nepal" },
  { id: "134", label: "🇳🇱 Netherlands", value: "netherlands" },
  { id: "135", label: "🇳🇿 New Zealand", value: "new_zealand" },
  { id: "136", label: "🇳🇮 Nicaragua", value: "nicaragua" },
  { id: "137", label: "🇳🇪 Niger", value: "niger" },
  { id: "138", label: "🇳🇬 Nigeria", value: "nigeria" },
  { id: "139", label: "🇲🇰 North Macedonia", value: "north_macedonia" },
  { id: "140", label: "🇳🇴 Norway", value: "norway" },
  { id: "141", label: "🇴🇲 Oman", value: "oman" },
  { id: "142", label: "🇵🇰 Pakistan", value: "pakistan" },
  { id: "143", label: "🇵🇼 Palau", value: "palau" },
  { id: "144", label: "🇵🇸 Palestine", value: "palestine" },
  { id: "145", label: "🇵🇦 Panama", value: "panama" },
  { id: "146", label: "🇵🇬 Papua New Guinea", value: "papua_new_guinea" },
  { id: "147", label: "🇵🇾 Paraguay", value: "paraguay" },
  { id: "148", label: "🇵🇪 Peru", value: "peru" },
  { id: "149", label: "🇵🇭 Philippines", value: "philippines" },
  { id: "150", label: "🇵🇱 Poland", value: "poland" },
  { id: "151", label: "🇵🇹 Portugal", value: "portugal" },
  { id: "152", label: "🇶🇦 Qatar", value: "qatar" },
  { id: "153", label: "🇷🇴 Romania", value: "romania" },
  { id: "154", label: "🇷🇺 Russia", value: "russia" },
  { id: "155", label: "🇷🇼 Rwanda", value: "rwanda" },
  { id: "156", label: "🇰🇳 Saint Kitts and Nevis", value: "saint_kitts_and_nevis" },
  { id: "157", label: "🇱🇨 Saint Lucia", value: "saint_lucia" },
  { id: "158", label: "🇻🇨 Saint Vincent and the Grenadines", value: "saint_vincent_and_the_grenadines" },
  { id: "159", label: "🇼🇸 Samoa", value: "samoa" },
  { id: "160", label: "🇸🇲 San Marino", value: "san_marino" },
  { id: "161", label: "🇸🇹 Sao Tome and Principe", value: "sao_tome_and_principe" },
  { id: "162", label: "🇸🇦 Saudi Arabia", value: "saudi_arabia" },
  { id: "163", label: "🇸🇳 Senegal", value: "senegal" },
  { id: "164", label: "🇷🇸 Serbia", value: "serbia" },
  { id: "165", label: "🇸🇨 Seychelles", value: "seychelles" },
  { id: "166", label: "🇸🇱 Sierra Leone", value: "sierra_leone" },
  { id: "167", label: "🇸🇬 Singapore", value: "singapore" },
  { id: "168", label: "🇸🇽 Sint Maarten", value: "sint_maarten" },
  { id: "169", label: "🇸🇰 Slovakia", value: "slovakia" },
  { id: "170", label: "🇸🇮 Slovenia", value: "slovenia" },
  { id: "171", label: "🇸🇧 Solomon Islands", value: "solomon_islands" },
  { id: "172", label: "🇸🇴 Somalia", value: "somalia" },
  { id: "173", label: "🇿🇦 South Africa", value: "south_africa" },
  { id: "174", label: "🇰🇷 South Korea", value: "south_korea" },
  { id: "175", label: "🇸🇸 South Sudan", value: "south_sudan" },
  { id: "176", label: "🇪🇸 Spain", value: "spain" },
  { id: "177", label: "🇱🇰 Sri Lanka", value: "sri_lanka" },
  { id: "178", label: "🇸🇩 Sudan", value: "sudan" },
  { id: "179", label: "🇸🇷 Suriname", value: "suriname" },
  { id: "180", label: "🇸🇪 Sweden", value: "sweden" },
  { id: "181", label: "🇨🇭 Switzerland", value: "switzerland" },
  { id: "182", label: "🇹🇼 Taiwan", value: "taiwan" },
  { id: "183", label: "🇹🇯 Tajikistan", value: "tajikistan" },
  { id: "184", label: "🇹🇿 Tanzania", value: "tanzania" },
  { id: "185", label: "🇹🇭 Thailand", value: "thailand" },
  { id: "186", label: "🇹🇱 Timor-Leste", value: "timor_leste" },
  { id: "187", label: "🇹🇬 Togo", value: "togo" },
  { id: "188", label: "🇹🇴 Tonga", value: "tonga" },
  { id: "189", label: "🇹🇹 Trinidad and Tobago", value: "trinidad_and_tobago" },
  { id: "190", label: "🇹🇳 Tunisia", value: "tunisia" },
  { id: "191", label: "🇹🇷 Turkey", value: "turkey" },
  { id: "192", label: "🇹🇲 Turkmenistan", value: "turkmenistan" },
  { id: "193", label: "🇹🇻 Tuvalu", value: "tuvalu" },
  { id: "194", label: "🇺🇬 Uganda", value: "uganda" },
  { id: "195", label: "🇺🇦 Ukraine", value: "ukraine" },
  { id: "196", label: "🇦🇪 United Arab Emirates", value: "united_arab_emirates" },
  { id: "197", label: "🇬🇧 United Kingdom", value: "united_kingdom" },
  { id: "198", label: "🇺🇸 United States of America", value: "united_states_of_america" },
  { id: "199", label: "🇺🇾 Uruguay", value: "uruguay" },
  { id: "200", label: "🇺🇿 Uzbekistan", value: "uzbekistan" },
  { id: "201", label: "🇻🇺 Vanuatu", value: "vanuatu" },
  { id: "202", label: "🇻🇦 Vatican", value: "vatican" },
  { id: "203", label: "🇻🇪 Venezuela", value: "venezuela" },
  { id: "204", label: "🇻🇳 Viet Nam", value: "viet_nam" },
  { id: "205", label: "🇾🇪 Yemen", value: "yemen" },
  { id: "206", label: "🇿🇲 Zambia", value: "zambia" },
  { id: "207", label: "🇿🇼 Zimbabwe", value: "zimbabwe" },
]
