// --- Mock Data ---

export const mockCustomer = {
  id: "CUS-2024-00847",
  type: "individual",
  riskRating: "high",
  fullName: "Aleksandr Petrov Volkov",
  aliases: ["A. Volkov", "Alex Petrov", "Aleksandr P. Volkov"],
  dateOfBirth: "1978-03-14",
  nationality: "Russian Federation",
  countryOfResidence: "Cyprus",
  idDocument: "Passport",
  idNumber: "72 4185 ****",
  occupation: "Investment Consultant",
  pep: true,
  onboardingDate: "2021-06-15",
  lastReviewDate: "2025-11-20",
  status: "under_review",
  accountManager: "M. Richardson",
};

export const mockOsintResults = {
  status: "needs_review",
  lastScanDate: "2026-02-19T14:32:00Z",
  scanDuration: "3m 42s",
  triggeredBy: "Scheduled Review",
  sourcesChecked: [
    {
      name: "OFAC SDN List",
      category: "Sanctions",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 0,
    },
    {
      name: "EU Consolidated List",
      category: "Sanctions",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 1,
    },
    {
      name: "UN Security Council",
      category: "Sanctions",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 0,
    },
    {
      name: "HM Treasury",
      category: "Sanctions",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 0,
    },
    {
      name: "World-Check (Refinitiv)",
      category: "PEP / Adverse",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 3,
    },
    {
      name: "Dow Jones Watchlist",
      category: "PEP / Adverse",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 2,
    },
    {
      name: "LexisNexis",
      category: "Media",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 4,
    },
    {
      name: "Google News",
      category: "Media",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 6,
    },
    {
      name: "ICIJ Offshore Leaks",
      category: "Public Records",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 1,
    },
    {
      name: "OpenCorporates",
      category: "Public Records",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 2,
    },
    {
      name: "Companies House (CY)",
      category: "Public Records",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 1,
    },
    {
      name: "Interpol Red Notices",
      category: "Law Enforcement",
      status: "checked",
      lastChecked: "2026-02-19",
      hits: 0,
    },
  ],
  adverseMedia: [
    {
      id: "AM-001",
      headline: "Cyprus Investment Firm Linked to Sanctions Evasion Probe",
      source: "Financial Times",
      publishDate: "2025-09-12",
      summary:
        "A Nicosia-based consultancy, where A. Volkov serves as senior advisor, is reportedly under investigation by Cypriot financial authorities for facilitating investments potentially linked to sanctioned Russian entities.",
      url: "https://ft.com/content/example-article-001",
      severity: "high",
      relevanceScore: 92,
      matchedTerms: ["Volkov", "Cyprus", "sanctions evasion"],
    },
    {
      id: "AM-002",
      headline: "EU Widens Crackdown on Russian Money Flows Through Mediterranean",
      source: "Reuters",
      publishDate: "2025-11-03",
      summary:
        "European regulators are intensifying scrutiny of Russian nationals operating financial advisory services in Cyprus, Malta, and Greece. Several individuals matching the profile of known investment consultants are under review.",
      url: "https://reuters.com/example-article-002",
      severity: "medium",
      relevanceScore: 74,
      matchedTerms: ["Russian nationals", "Cyprus", "financial advisory"],
    },
    {
      id: "AM-003",
      headline: "Leaked Documents Reveal Complex Offshore Structures",
      source: "OCCRP",
      publishDate: "2024-06-20",
      summary:
        "Investigative journalists identify a network of shell companies in BVI and Cyprus with beneficial ownership traced to several Russian nationals, including a person named 'A.P. Volkov' listed as director of two entities.",
      url: "https://occrp.org/example-investigation-003",
      severity: "critical",
      relevanceScore: 88,
      matchedTerms: ["A.P. Volkov", "shell companies", "BVI", "Cyprus"],
    },
    {
      id: "AM-004",
      headline: "PEP Screening Gaps Highlighted in European Banking Report",
      source: "Compliance Week",
      publishDate: "2025-04-10",
      summary:
        "A compliance industry report cites cases where politically exposed persons with Russian connections were inadequately screened by EU financial institutions. General reference, no direct mention of subject.",
      url: "https://complianceweek.com/example-004",
      severity: "low",
      relevanceScore: 35,
      matchedTerms: ["PEP", "Russian", "screening"],
    },
  ],
  sanctionsPep: [
    {
      id: "SP-001",
      listName: "EU Consolidated Sanctions List",
      listType: "sanctions",
      matchScore: 72,
      matchedName: "Aleksandr P. Volkov",
      details:
        "Partial name match found. Listed individual: 'Aleksander Petrovich Volkov' - associated with state-owned enterprise. DOB differs by 2 years. Requires manual review.",
      listDate: "2024-03-15",
      status: "potential_match",
      source: "EU External Action Service",
    },
    {
      id: "SP-002",
      listName: "World-Check PEP Database",
      listType: "pep",
      matchScore: 95,
      matchedName: "Aleksandr Petrov Volkov",
      details:
        "Confirmed PEP classification. Subject previously served as advisor to the Deputy Minister of Economic Development (2012-2017). Close associate of multiple senior government officials.",
      listDate: "2023-08-01",
      status: "confirmed_match",
      source: "Refinitiv World-Check",
    },
    {
      id: "SP-003",
      listName: "Dow Jones PEP / Sanctions",
      listType: "pep",
      matchScore: 91,
      matchedName: "Aleksandr P. Volkov",
      details:
        "Flagged as politically exposed person. Historical role as government economic advisor. Associated entities flagged in prior AML investigations.",
      listDate: "2023-06-15",
      status: "confirmed_match",
      source: "Dow Jones Risk & Compliance",
    },
    {
      id: "SP-004",
      listName: "OFAC SDN List",
      listType: "sanctions",
      matchScore: 28,
      matchedName: "Volkov, Aleksandr",
      details:
        "Low-confidence name match only. No corroborating identifiers (DOB, nationality, address) match the listed individual. Assessed as false positive.",
      listDate: "2025-01-10",
      status: "false_positive",
      source: "US Treasury OFAC",
    },
  ],
  publicRecords: [
    {
      id: "PR-001",
      type: "Corporate Directorship",
      jurisdiction: "Cyprus",
      date: "2019-04-22",
      summary:
        "Director of Meridian Capital Advisory Ltd (HE 412XXX), registered in Limassol. Company active, annual filings current.",
      source: "Cyprus Department of Registrar",
      url: "https://efiling.drcor.mcit.gov.cy/",
    },
    {
      id: "PR-002",
      type: "Offshore Entity",
      jurisdiction: "British Virgin Islands",
      date: "2020-11-05",
      summary:
        "Listed as beneficial owner of Crestview Holdings Ltd (BVI). Entity appears in ICIJ Offshore Leaks database. Registered agent: Trident Trust.",
      source: "ICIJ Offshore Leaks DB",
      url: "https://offshoreleaks.icij.org/",
    },
    {
      id: "PR-003",
      type: "Property Record",
      jurisdiction: "Cyprus",
      date: "2021-02-18",
      summary:
        "Registered owner of residential property in Limassol (Land Registry ref. LS/2021/XXXXX). Estimated value EUR 1.2M.",
      source: "Cyprus Land Registry (public extract)",
      url: "#",
    },
  ],
  riskIndicators: [
    {
      id: "RI-001",
      category: "Sanctions Proximity",
      indicator: "Potential match on EU Consolidated Sanctions List",
      severity: "high",
      detail: "72% name match requires manual adjudication. DOB discrepancy noted.",
      source: "EU Sanctions Screening",
    },
    {
      id: "RI-002",
      category: "PEP Status",
      indicator: "Confirmed Politically Exposed Person",
      severity: "high",
      detail:
        "Former government economic advisor (2012-2017). Close associate tier flagged by two independent databases.",
      source: "World-Check / Dow Jones",
    },
    {
      id: "RI-003",
      category: "Adverse Media",
      indicator: "Named in sanctions evasion investigation reporting",
      severity: "critical",
      detail:
        "Direct name mention in Financial Times article citing Cypriot regulatory probe. Corroborated by OCCRP investigation.",
      source: "LexisNexis / Google News",
    },
    {
      id: "RI-004",
      category: "Complex Structures",
      indicator: "Beneficial owner of offshore entity in ICIJ leaks",
      severity: "high",
      detail:
        "BVI-registered entity linked to subject via ICIJ Offshore Leaks database. Registered through Trident Trust.",
      source: "ICIJ Offshore Leaks",
    },
    {
      id: "RI-005",
      category: "Jurisdiction Risk",
      indicator: "High-risk jurisdiction nexus (RU-CY-BVI)",
      severity: "medium",
      detail:
        "Russian national, resident in Cyprus, with BVI corporate structures. Multi-jurisdiction complexity increases AML risk.",
      source: "Internal Risk Assessment",
    },
  ],
  evidenceItems: [
    {
      id: "EV-001",
      type: "archived_page",
      label: "Financial Times Article Screenshot",
      source: "Financial Times",
      date: "2025-09-12",
      url: "https://web.archive.org/web/example-ft-article",
      hash: "sha256:a1b2c3d4e5f6...",
    },
    {
      id: "EV-002",
      type: "document",
      label: "ICIJ Offshore Leaks - Entity Report",
      source: "ICIJ",
      date: "2024-06-20",
      url: "https://offshoreleaks.icij.org/",
      hash: "sha256:f6e5d4c3b2a1...",
    },
    {
      id: "EV-003",
      type: "screenshot",
      label: "World-Check PEP Record Extract",
      source: "Refinitiv World-Check",
      date: "2026-02-19",
      url: "#internal-system",
      hash: "sha256:1a2b3c4d5e6f...",
    },
    {
      id: "EV-004",
      type: "link",
      label: "OpenCorporates - Meridian Capital Advisory",
      source: "OpenCorporates",
      date: "2026-02-19",
      url: "https://opencorporates.com/companies/cy/HE412XXX",
    },
    {
      id: "EV-005",
      type: "document",
      label: "EU Consolidated Sanctions List - Match Report",
      source: "EU External Action Service",
      date: "2026-02-19",
      url: "#internal-screening-report",
      hash: "sha256:9f8e7d6c5b4a...",
    },
  ],
  analystNotes: [
    {
      id: "AN-001",
      author: "J. Chen",
      date: "2026-02-19T15:10:00Z",
      content:
        "OSINT scan completed. Multiple high-severity indicators flagged. EU sanctions partial match requires manual adjudication — DOB discrepancy suggests possible false positive but name and nationality alignment is concerning. PEP status is confirmed by two independent databases. Adverse media coverage is substantial and directly names the subject in connection with sanctions evasion allegations. Recommend escalation to senior compliance officer for EDD.",
      action: "Escalate for Enhanced Due Diligence",
    },
    {
      id: "AN-002",
      author: "M. Richardson",
      date: "2025-11-20T09:30:00Z",
      content:
        "Annual periodic review completed. No material changes since last review. PEP status unchanged. New adverse media hits flagged for next cycle review. Account activity within expected parameters.",
    },
  ],
};
