import { toast } from "sonner";

/**
 * Downloads a server-rendered compliance report PDF.
 *
 * The document is generated by the API and streamed through an authenticated
 * proxy route (`/api/<kind>/<id>/export-pdf`) rather than printed from the DOM:
 * a filed report has to be byte-identical for every officer and paginated
 * properly, which printing the page cannot guarantee.
 *
 * Shared by the ECDD and SMR detail screens and their registers so the four
 * call sites cannot drift on filename, error handling or cleanup.
 *
 * @param {"ecdd"|"smr"} kind    which report family
 * @param {string}       id      report _id
 * @param {string}       [label] uid used for the filename; falls back to the id
 * @returns {Promise<boolean>}   true when the file was handed to the browser
 */
export async function downloadReportPdf({ kind, id, label }) {
  if (!id) {
    toast.error("This report has no id to export.");
    return false;
  }

  let objectUrl;
  try {
    const response = await fetch(`/api/${kind}/${id}/export-pdf`);
    if (!response.ok) {
      throw new Error(
        response.status === 404
          ? "Report not found on the server."
          : `Export failed (${response.status})`,
      );
    }

    const blob = await response.blob();
    objectUrl = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = objectUrl;
    link.download = `${kind.toUpperCase()}_${label || id}.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    return true;
  } catch (error) {
    toast.error(error.message || "Could not export the report");
    return false;
  } finally {
    // Revoked in `finally` so a failure part-way through cannot leak the blob.
    if (objectUrl) URL.revokeObjectURL(objectUrl);
  }
}
